---
abstract: 'Track and report execution time for parts of code'
author:
  - 'Author:      Jason Moore - jmoore@sober.com (no longer valid)'
  - 'Jason Moore'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Timer
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Time::HiRes: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/szabgab/Devel-Timer
version: 0.05
